### ISSUE TITLE
### 3. **Issue: Implement Search Feature**

### ISSUE THREAD

**Issue by ajinkyabridgelabz** [ajinkyabridgelabz/online-library-management-system#3]
**Description**:
Allow users to search for books by title, author, or genre. This should be  a backend  
feature.

**Tasks**:
- [ ] Implement a search method in `BookService` that takes in a query and searches based on title, 
author, or genre.
- [ ] Add a GET endpoint in `BookController` like `/books/search?query=XYZ`.

**Comment by ajinkyabridgelabz** [comment]
Do this task asap

**Comment by ajinkyabridgelabz** [comment]
Please refer https://github.com/ajinkyabridgelabz/online-library-management-system/blob/main/branchingreadme.md

**Comment by naveenkumargorakala** [comment]
My merge was accepted
