### ISSUE TITLE
### 5. **Issue: Delete a Book**

### ISSUE THREAD

**Issue by ajinkyabridgelabz** [ajinkyabridgelabz/online-library-management-system#6]
**Description**:
Facilitate the removal of books from the system.

**Tasks**:
- [x] Introduce a `deleteBook(Long bookId)` method in `BookService`.
- [ ] Set up a DELETE endpoint in `BookController` like `/books/{bookId}`.

**Comment by ajinkyabridgelabz** [comment]
Please do it asap

**Comment by ajinkyabridgelabz** [comment]
Please refer it https://github.com/ajinkyabridgelabz/online-library-management-system/blob/main/branchingreadme.md

**Comment by satya1-2** [comment]
resolved the issue
